# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cda1abc13ff880674cc61ef53c5e16d30d5f8570fc27f3c95205ca97a7cdfa0ed97a0e9f2088eba2fd8e39487c7526ac8ea0c3864934bf24531dec4dadd53702

test:
  secret_key_base: 9be9f3f74dde18c7f120ee150dfefe75e0f8a056ae0808dd279bdcf6ba4e8e9b805fc98d1bacb73a2dd5c5a1a5512afa9b66be7e50fec658aa53967ed426e1b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
